export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE';

export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILURE = 'UPDATE_CART_FAILURE';

export const CART_DETAILS_FETCH_SUCCESS = 'CART_DETAILS_FETCH_SUCCESS'
export const CART_DETAILS_FETCH_FAILURE = 'CART_DETAILS_FETCH_FAILURE'

export const CLEAR_CART = 'CLEAR_CART';